#################################################################################
#
# name: KECorrection.mac
# date: 10 Jan 16
# auth; Zach Hartwig
# mail: hartwig@psfc.mit.edu
#
# desc: Macro to be used to determine the kinetic energy correction factor,
#       which is the difference between known incident KE and energy deposited
#       in the detector. The difference (for particles whose range is less than
#       the total length of material along the detectors Z-axis) is due to
#       energy loss in the scintillator wrappings and light shield layers. A
#       ROOT output file should be created via the /Sparrow/dataOutput/init
#       command such that the run-level data necessary to make the correction
#       will be produced. See the ROOT analysis script 'KECorrection.cc' in the
#       KECorrection directory of the SparrowAnalysis GitHub repository.
#
#################################################################################

# Correction is made assuming particle beams are incident perfectly
# along the Z-axis of the detector for simplicity
{standard}

##########
# Arrays #
##########

# Select the ASIM array (ID == 0) representing the west-core
# scintillator pair and ensure energy thresholding is enabled

/ASIM/array/select 0
/ASIM/array/setThresholdType energy

##########
# Proton #
##########

/gps/particle proton

/Sparrow/dataOutput/setFileName KECorrectionProton.root
/Sparrow/dataOutput/init

/gps/ene/mono 5 MeV
/ASIM/array/setLowerEnergyThreshold 0 MeV
/run/beamOn 50000

/gps/ene/mono 7.5 MeV
/ASIM/array/setLowerEnergyThreshold 2.5 MeV
/run/beamOn 50000

/gps/ene/mono 10 MeV
/ASIM/array/setLowerEnergyThreshold 5 MeV
/run/beamOn 50000

/gps/ene/mono 12.5 MeV
/ASIM/array/setLowerEnergyThreshold 7.5 MeV
/run/beamOn 50000

/gps/ene/mono 15 MeV
/ASIM/array/setLowerEnergyThreshold 10 MeV
/run/beamOn 50000

/gps/ene/mono 17.5 MeV
/ASIM/array/setLowerEnergyThreshold 12.5 MeV
/run/beamOn 50000

/gps/ene/mono 20 MeV
/ASIM/array/setLowerEnergyThreshold 15 MeV
/run/beamOn 50000

/gps/ene/mono 22.5 MeV
/ASIM/array/setLowerEnergyThreshold 17.5 MeV
/run/beamOn 50000

/gps/ene/mono 25 MeV
/ASIM/array/setLowerEnergyThreshold 20 MeV
/run/beamOn 50000

/gps/ene/mono 27.5 MeV
/ASIM/array/setLowerEnergyThreshold 22.5 MeV
/run/beamOn 50000

/gps/ene/mono 30 MeV
/ASIM/array/setLowerEnergyThreshold 25 MeV
/run/beamOn 50000

/gps/ene/mono 32.5 MeV
/ASIM/array/setLowerEnergyThreshold 27.5 MeV
/run/beamOn 50000

/gps/ene/mono 35 MeV
/ASIM/array/setLowerEnergyThreshold 30 MeV
/run/beamOn 50000

/gps/ene/mono 37.5 MeV
/ASIM/array/setLowerEnergyThreshold 32.5 MeV
/run/beamOn 50000

/gps/ene/mono 40 MeV
/ASIM/array/setLowerEnergyThreshold 35 MeV
/run/beamOn 50000

/gps/ene/mono 42.5 MeV
/ASIM/array/setLowerEnergyThreshold 37.5 MeV
/run/beamOn 50000

/gps/ene/mono 45 MeV
/ASIM/array/setLowerEnergyThreshold 40 MeV
/run/beamOn 50000

/gps/ene/mono 47.5 MeV
/ASIM/array/setLowerEnergyThreshold 42.5 MeV
/run/beamOn 50000

/gps/ene/mono 50 MeV
/ASIM/array/setLowerEnergyThreshold 45 MeV
/run/beamOn 50000

/gps/ene/mono 52.5 MeV
/ASIM/array/setLowerEnergyThreshold 47.5 MeV
/run/beamOn 50000

/gps/ene/mono 55 MeV
/ASIM/array/setLowerEnergyThreshold 50 MeV
/run/beamOn 50000

/gps/ene/mono 57.5 MeV
/ASIM/array/setLowerEnergyThreshold 52.5 MeV
/run/beamOn 50000

/gps/ene/mono 60 MeV
/ASIM/array/setLowerEnergyThreshold 55 MeV
/run/beamOn 50000

/gps/ene/mono 62.5 MeV
/ASIM/array/setLowerEnergyThreshold 57.5 MeV
/run/beamOn 50000

/gps/ene/mono 65 MeV
/ASIM/array/setLowerEnergyThreshold 60 MeV
/run/beamOn 50000

/gps/ene/mono 67.5 MeV
/ASIM/array/setLowerEnergyThreshold 62.5 MeV
/run/beamOn 50000

/gps/ene/mono 70 MeV
/ASIM/array/setLowerEnergyThreshold 65 MeV
/run/beamOn 50000

/gps/ene/mono 72.5 MeV
/ASIM/array/setLowerEnergyThreshold 67.5 MeV
/run/beamOn 50000

/gps/ene/mono 75 MeV
/ASIM/array/setLowerEnergyThreshold 70 MeV
/run/beamOn 50000

/gps/ene/mono 77.5 MeV
/ASIM/array/setLowerEnergyThreshold 72.5 MeV
/run/beamOn 50000

/gps/ene/mono 80 MeV
/ASIM/array/setLowerEnergyThreshold 75 MeV
/run/beamOn 50000

/gps/ene/mono 82.5 MeV
/ASIM/array/setLowerEnergyThreshold 77.5 MeV
/run/beamOn 50000

/gps/ene/mono 85 MeV
/ASIM/array/setLowerEnergyThreshold 80 MeV
/run/beamOn 50000


/Sparrow/dataOutput/write

############
# Electron #
############

/gps/particle e-

/Sparrow/dataOutput/setFileName KECorrectionElectron.root
/Sparrow/dataOutput/init

/gps/ene/mono 1 MeV
/ASIM/array/setLowerEnergyThreshold 0 MeV
/run/beamOn 50000

/gps/ene/mono 1.5 MeV
/ASIM/array/setLowerEnergyThreshold 0 MeV
/run/beamOn 50000

/gps/ene/mono 2 MeV
/ASIM/array/setLowerEnergyThreshold 0 MeV
/run/beamOn 50000

/gps/ene/mono 2.5 MeV
/ASIM/array/setLowerEnergyThreshold 0 MeV
/run/beamOn 50000

/gps/ene/mono 3 MeV
/ASIM/array/setLowerEnergyThreshold 0 MeV
/run/beamOn 50000

/gps/ene/mono 3.5 MeV
/ASIM/array/setLowerEnergyThreshold 0 MeV
/run/beamOn 50000

/gps/ene/mono 4 MeV
/ASIM/array/setLowerEnergyThreshold 0 MeV
/run/beamOn 50000

/gps/ene/mono 4.5 MeV
/ASIM/array/setLowerEnergyThreshold 0 MeV
/run/beamOn 50000

/gps/ene/mono 5 MeV
/ASIM/array/setLowerEnergyThreshold 0 MeV
/run/beamOn 50000

/gps/ene/mono 5.5 MeV
/ASIM/array/setLowerEnergyThreshold 0 MeV
/run/beamOn 50000

/gps/ene/mono 6 MeV
/ASIM/array/setLowerEnergyThreshold 0 MeV
/run/beamOn 50000

/gps/ene/mono 6.5 MeV
/ASIM/array/setLowerEnergyThreshold 0 MeV
/run/beamOn 50000

/gps/ene/mono 7 MeV
/ASIM/array/setLowerEnergyThreshold 0 MeV
/run/beamOn 50000

/gps/ene/mono 7.5 MeV
/ASIM/array/setLowerEnergyThreshold 0 MeV
/run/beamOn 50000

/gps/ene/mono 8 MeV
/ASIM/array/setLowerEnergyThreshold 0 MeV
/run/beamOn 50000

/gps/ene/mono 8.5 MeV
/ASIM/array/setLowerEnergyThreshold 0 MeV
/run/beamOn 50000

/gps/ene/mono 9 MeV
/ASIM/array/setLowerEnergyThreshold 0 MeV
/run/beamOn 50000

/gps/ene/mono 9.5 MeV
/ASIM/array/setLowerEnergyThreshold 0 MeV
/run/beamOn 50000

/gps/ene/mono 10 MeV
/ASIM/array/setLowerEnergyThreshold 0 MeV
/run/beamOn 50000

/gps/ene/mono 10.5 MeV
/ASIM/array/setLowerEnergyThreshold 0 MeV
/run/beamOn 50000

/gps/ene/mono 11 MeV
/ASIM/array/setLowerEnergyThreshold 0 MeV
/run/beamOn 50000

/gps/ene/mono 11.5 MeV
/ASIM/array/setLowerEnergyThreshold 0 MeV
/run/beamOn 50000

/gps/ene/mono 12 MeV
/ASIM/array/setLowerEnergyThreshold 0 MeV
/run/beamOn 50000

/gps/ene/mono 12.5 MeV
/ASIM/array/setLowerEnergyThreshold 0 MeV
/run/beamOn 50000

/gps/ene/mono 13 MeV
/ASIM/array/setLowerEnergyThreshold 0 MeV
/run/beamOn 50000

/gps/ene/mono 13.5 MeV
/ASIM/array/setLowerEnergyThreshold 0 MeV
/run/beamOn 50000

/gps/ene/mono 14 MeV
/ASIM/array/setLowerEnergyThreshold 0 MeV
/run/beamOn 50000

/gps/ene/mono 14.5 MeV
/ASIM/array/setLowerEnergyThreshold 0 MeV
/run/beamOn 50000

/gps/ene/mono 15 MeV
/ASIM/array/setLowerEnergyThreshold 0 MeV
/run/beamOn 50000

/gps/ene/mono 15.5 MeV
/ASIM/array/setLowerEnergyThreshold 0 MeV
/run/beamOn 50000

/gps/ene/mono 16 MeV
/ASIM/array/setLowerEnergyThreshold 0 MeV
/run/beamOn 50000

/gps/ene/mono 16.5 MeV
/ASIM/array/setLowerEnergyThreshold 0 MeV
/run/beamOn 50000

/gps/ene/mono 17 MeV
/ASIM/array/setLowerEnergyThreshold 0 MeV
/run/beamOn 50000

/gps/ene/mono 17.5 MeV
/ASIM/array/setLowerEnergyThreshold 0 MeV
/run/beamOn 50000

/gps/ene/mono 18 MeV
/ASIM/array/setLowerEnergyThreshold 0 MeV
/run/beamOn 50000

/gps/ene/mono 18.5 MeV
/ASIM/array/setLowerEnergyThreshold 0 MeV
/run/beamOn 50000

/gps/ene/mono 19 MeV
/ASIM/array/setLowerEnergyThreshold 0 MeV
/run/beamOn 50000

/gps/ene/mono 19.5 MeV
/ASIM/array/setLowerEnergyThreshold 0 MeV
/run/beamOn 50000

/gps/ene/mono 20 MeV
/ASIM/array/setLowerEnergyThreshold 0 MeV
/run/beamOn 50000


/Sparrow/dataOutput/write
